name: functions test

on:
  pull_request:
    branches: [master]
    paths:
      - "functions/**"
      - ".github/workflows/function-test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install dependencies
        run: cd functions/ && npm ci

      - name: Run test
        run: cd functions/ && npm test
        env:
          PARTNER_TAG: ${{ secrets.PARTNER_TAG }}
          AMAZON_PAAPI_SECRET: ${{ secrets.AMAZON_PAAPI_SECRET }}
          AMAZON_PAAPI_KEY: ${{ secrets.AMAZON_PAAPI_KEY }}
